### ISSUE TITLE
无法登录和下载了

### ISSUE THREAD

**Issue by smarkoo** [kkHAIKE/fake115#98]
# 不遵守规范直接 close

### 我能否访问/Ping通 rawgit.com (最近地方 DNS 有屏蔽此域名)
可以拼通
### 我是否点击了主界面 "使用帐号登录"，重复刷新了几次
是的
### 我的操作系统是，版本是
win10 21H2
### 我的浏览器是，版本是
chrome 97.0.4692.99
### 我的油猴插件是(Violent/Grease/Tamper)monkey，版本是
tamper 4.14
### 我遇到了什么问题，截图
无法登录和下载了

**Comment by kkHAIKE** [comment]
现在官方已经放开浏览器登录了，不用插件进行辅助登录了
可以使用 fake115d.user.js 插件进行下载。
我刚刚测试过是有效的

如果无效请贴出日志和截图。

**Comment by smarkoo** [comment]
可以使用chrome登录，但必须手机短信验证登录或者手机端扫描二维码登录。
截图：https://uploadbeta.com/share-image/hgG
日志：
?cid=1907192013214566093&offset=0&tab=download&mode=wangpan:1420 A parser-blocking, cross site (i.e. different eTLD+1) script, https://s9.cnzz.com/z_stat.php?id=1279056547, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
(anonymous) @ ?cid=1907192013214566093&offset=0&tab=download&mode=wangpan:1420
?cid=1907192013214566093&offset=0&tab=download&mode=wangpan:1420 A parser-blocking, cross site (i.e. different eTLD+1) script, https://s9.cnzz.com/z_stat.php?id=1279056547, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
(anonymous) @ ?cid=1907192013214566093&offset=0&tab=download&mode=wangpan:1420
z_stat.php:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
115.com/:1 Unchecked runtime.lastError: The message port closed before a response was received.
115.com/:1 Error handling response: TypeError: Cannot read properties of undefined (reading 'msg')
    at chrome-extension://fjccjnfkdkdmjohojoggodkigkjkkjhl/contentscript.js:41:11
??plug/workerHelper/workerClient.js,login/loginworker/pageApi.js?v=1643190541:1 init_worker loginWebsocketWorker undefined
??plug/workerHelper/workerClient.js,login/loginworker/pageApi.js?v=1643190541:1 Worker MainKey loginWebsocketWorker_1643976805023_1 0
bridge.html:1 Unchecked runtime.lastError: The message port closed before a response was received.
bridge.html:1 Error handling response: TypeError: Cannot read properties of undefined (reading 'msg')
    at chrome-extension://fjccjnfkdkdmjohojoggodkigkjkkjhl/contentscript.js:41:11
??libs/jquery-1.7.2.js,oofUtil.js,paths.js,oofUtil/validate.js,oofUtil/cookies.js,oofUtil/stringHelper.js,shell.js,plug/copy/copy.js,oofUtil/template.js?v=1643190541:3 Array(2) '加载bridge-passportapi'
??libs/jquery-1.7.2.js,oofUtil.js,paths.js,oofUtil/validate.js,oofUtil/cookies.js,oofUtil/stringHelper.js,shell.js,plug/copy/copy.js,oofUtil/template.js?v=1643190541:3 Array(2) '加载bridge-passportapi-成功 https://passportapi.115.com/bridge_assets.html?cb_key=iframe_cb_key__1643976806569_2&_t1643976806569 : https://passportapi.115.com/bridge_assets.html?cb_key=iframe_cb_key__1643976806569_2&_t1643976806569'
??libs/jquery-1.7.2.js,oofUtil.js,paths.js,oofUtil/validate.js,oofUtil/cookies.js,oofUtil/stringHelper.js,shell.js,plug/copy/copy.js,oofUtil/template.js?v=1643190541:3 Array(2)
??libs/jquery-1.7.2.js,oofUtil.js,paths.js,oofUtil/validate.js,oofUtil/cookies.js,oofUtil/stringHelper.js,shell.js,plug/copy/copy.js,oofUtil/template.js?v=1643190541:3 Array(3) 'https://passportapi.115.com/bridge_assets.html?cb_key=iframe_cb_key__1643976806569_2&_t1643976806569'
bridge_assets.html:1 Unchecked runtime.lastError: The message port closed before a response was received.
bridge_assets.html:1 Error handling response: TypeError: Cannot read properties of undefined (reading 'msg')
    at chrome-extension://fjccjnfkdkdmjohojoggodkigkjkkjhl/contentscript.js:41:11
DevTools failed to load source map: Could not load content for chrome-extension://chinfkfmaefdlchhempbfgbdagheknoj/global/js/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/md5.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
